# Generated by Django 5.1.1 on 2025-09-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
